# Generated by Django 4.1.7 on 2023-03-23 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to='categories'),
        ),
        migrations.AddField(
            model_name='category',
            name='primary',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='bought',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='sorting_index',
            field=models.IntegerField(default=0),
        ),
    ]
