# Generated by Django 4.1.7 on 2023-03-24 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_limited'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='producer',
            field=models.TextField(default='Nvidia'),
        ),
    ]
