# Generated by Django 4.1.7 on 2023-03-24 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_product_options_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reviews', to='shop.product'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
