# Generated by Django 4.1.7 on 2023-03-24 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_reviews_product_alter_reviews_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reviews_num',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
