# Generated by Django 4.1.7 on 2023-03-28 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='free_shipping_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
